version: "3"

volumes:
  media:
    driver: local
  mariadb:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    expose:
      - "8080"
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - VIRTUAL_HOST=${DOMAINS}
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      # - ./media:/mnt/data
      - media:/mnt/data
    labels:
      - docker-volume-backup.stop-during-backup=service-1

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb:/var/lib/mysql
    labels:
      - docker-volume-backup.stop-during-backup=service-2

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
    labels:
      - docker-volume-backup.stop-during-backup=service-3

  backup_media: &backup_service
    image: offen/docker-volume-backup:latest
    container_name: backup_media
    restart: always
    env_file: ./backup.env
    environment: &backup_environment
      BACKUP_STOP_CONTAINER_LABEL: service-1
    volumes:
      - media:/backup/owncloud-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/usb2/service-backups/owncloud:/archive

  backup_mariadb:
    <<: *backup_service
    container_name: backup_mariadb
    restart: always
    env_file: ./backup.env
    environment:
      <<: *backup_environment
      BACKUP_STOP_CONTAINER_LABEL: service-2
    volumes:
      - mariadb:/backup/mariadb-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/usb2/service-backups/mariadb:/archive

  backup_redis:
    <<: *backup_service
    container_name: backup_redis
    restart: always
    env_file: ./backup.env
    environment:
      <<: *backup_environment
      BACKUP_STOP_CONTAINER_LABEL: service-3
    volumes:
      - redis:/backup/redis-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/usb2/service-backups/redis:/archive

networks:
   default:
     external:
       name: ${NETWORK}
